### ISSUE TITLE
Missing a Question

### ISSUE THREAD

**Issue by NimeeshS** [cpinitiative/ide#121] opened 2023-11-10 00:58 UTC
Missing the Cow College Question (http://usaco.org/index.php?page=viewproblem2&cpid=1251)

**Comment by thecodingwizard** [comment] 2023-11-12 05:31
The search is done through Algolia on the `usacoProblems`

**Comment by thecodingwizard** [comment] 2023-11-17 18:19
(I assume the issue is referring to the problem search feature within the USACO Guide IDE...)

**Comment by thecodingwizard** [comment] 2023-12-26 07:44
Fixed by https://github.com/cpinitiative/usaco-guide/pull/4086. Thanks @devo1ution !

**Closed by thecodingwizard** 2023-12-26 07:44 UTC
