### ISSUE TITLE
`Settings Modal` is Displacing when going through tabs

### ISSUE THREAD

**Issue by devishraq** [cpinitiative/ide#156] opened 2024-08-06 08:20 UTC
### Problem Description
When users open the settings modal and navigate through the tabs, specifically the Judge tab, the entire modal shifts. This issue is caused by the use of the overflow-y-auto class, which hides the scrollbar when on the Judge tab.

### Simplistic Solution
The proposed solution is to set overflow-y: scroll; to ensure the scrollbar is always present, thereby preventing the displacement. Additionally, the scrollbar should be hidden but its functionality retained.

Uploading Screen-Recording-2024-08-06T08_23_21.970Z.mp4…

**Comment by devishraq** [comment] 2024-08-06 08:21
I think I would be able to solve this.....Any one please assign me this!

**Comment by devishraq** [comment] 2024-08-07 04:01
@thecodingwizard! Which approach will be much better removing the scrollbar while the settings modal is opened but keeping scrolling functionalities or just using `overflow-y: scroll`?

The first approach will be better I think....

**Comment by thecodingwizard** [comment] 2024-08-07 04:42
Sorry could you re-upload the screen recording? I don't think it uploaded properly and I can't reproduce this issue on my end (though I'm on a mac).

The first approach is indeed better but I'm not actually sure how this can be done (maybe scrollbar width can be configured with CSS? not sure...)

**Comment by devishraq** [comment] 2024-08-07 04:54
Uploading Screen-Recording-2024-08-06T08_23_21.970Z.mp4…

**Comment by devishraq** [comment] 2024-08-07 04:57
@thecodingwizard I am unable to upload it here....I don't why!....But here is a third-part link from jumpshare:-
https://jumpshare.com/s/sLqkXGVLViKLRES3wTYu

**Comment by devishraq** [comment] 2024-08-07 05:06
Here you can see : I forked, cloned, and edited and the result:-
https://jmp.sh/s/ChCcddzt0nJtzF1oZ1KT
I have taken the second approach as it may slightly improve the cleanliness of the UI!

**Comment by devishraq** [comment] 2024-08-13 11:46
@thecodingwizard ! can you check the videos and the pull request kindly?

**Comment by thecodingwizard** [comment] 2024-08-23 00:11
Closed via #157 , thank you @devishraq !

**Closed by thecodingwizard** 2024-08-23 00:11 UTC
