### ISSUE TITLE
Can't run code locally...

### ISSUE THREAD

**Issue by cirex-web** [cpinitiative/ide#66] opened 2022-04-29 22:56 UTC
After following the instructions to start a local development server and doing `yarn dev`, I ended up with a bunch of ERR_UNSUPPORTED_DIR_IMPORT errors.

Does anyone know how to fix this? I want to check out the codebase lol

Thanks!
<img width="731" alt="image" src="https://user-images.githubusercontent.com/57322506/166078419-3f248a23-8685-4474-8424-79b5ff16da52.png">

**Comment by thecodingwizard** [comment] 2022-06-18 08:07
I'm going to close this since I can't reproduce this either. If you figure out how to reproduce this issue though, please add a comment and reopen! Thanks!

**Closed by thecodingwizard** 2022-06-18 08:07 UTC
